//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise_Ych_06._25
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.LeasingContracts = new HashSet<LeasingContracts>();
        }
    
        public int client_id { get; set; }
        public string client_name { get; set; }
        public string contact_phone { get; set; }
        public string contact_email { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string tax_id_number { get; set; }
        public Nullable<decimal> credit_rating { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeasingContracts> LeasingContracts { get; set; }
    }
}
