//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise_Ych_06._25
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int insurance_id { get; set; }
        public int product_id { get; set; }
        public string policy_number { get; set; }
        public string provider { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public decimal premium { get; set; }
        public decimal coverage_amount { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
