//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise_Ych_06._25
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeasingContracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeasingContracts()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int contract_id { get; set; }
        public int client_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public decimal monthly_payment { get; set; }
        public decimal total_value { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public string status { get; set; }
        public Nullable<int> sales_rep_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
