//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise_Ych_06._25
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int maintenance_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime maintenance_date { get; set; }
        public string maintenance_type { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string description { get; set; }
        public string performed_by { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
