//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise_Ych_06._25
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public int contract_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public decimal amount { get; set; }
        public string payment_method { get; set; }
        public Nullable<int> received_by { get; set; }
        public string notes { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual LeasingContracts LeasingContracts { get; set; }
    }
}
