//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise_Ych_06._25
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActiveContractsWithDetails
    {
        public int contract_id { get; set; }
        public string client_name { get; set; }
        public string product_name { get; set; }
        public string category { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public decimal monthly_payment { get; set; }
        public decimal total_value { get; set; }
        public string sales_representative { get; set; }
        public Nullable<int> months_remaining { get; set; }
    }
}
