//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practise_Ych_06._25
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductFinancialAnalytics
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string category { get; set; }
        public decimal purchase_price { get; set; }
        public decimal current_value { get; set; }
        public Nullable<int> lease_count { get; set; }
        public Nullable<decimal> total_lease_value { get; set; }
        public Nullable<decimal> total_maintenance_cost { get; set; }
        public Nullable<decimal> total_insurance_cost { get; set; }
    }
}
